DATA:
  rootdir: '/Datasets/'
  datasets: ['parking','kitti','malaga']
  curr_dataset: 'parking'
  init_img_1: '/images/img_00000.png'
  init_img_2: '/images/img_00005.png'

FEATURES:
  detectors: ['shi_tomasi', 'harris', 'sift']
  curr_detector: 2

HARRIS:
  cv2: True
  kappa: 0.08
  corner_patch_size: 9
  num_keypoints: 200
  nonmaximum_supression_radius: 8
  descriptor_radius: 9
  match_lambda: 4

SHI_TOMASI:
  cv2: True # Not implemented yet - can't make it work
  num_keypoints: 200
  corner_patch_size: 9
  nonmaximum_supression_radius: 8
  descriptor_radius: 9
  match_lambda: 4
  quality_level: 0.01

SIFT:
  nfeatures: 0 
  contrast_threshold: 0.04
  sigma: 1.6
  n_otave_layers: 3

MATCHING:
  k: 2
  ratio: 0.75

LK:
  win_size: 11
  max_level: 3
  crit_count: 30
  crit_eps: 0.01

RANSAC:
  prob: 0.999
  threshold: 2.0

PNPRANSAC:
  iterations: 1000
  reprojection_error: 8.0
  prob: 0.99

CONT_VO:
  baseline_angle_thresh: 5 # Degree threshold for baseline angle
  kp_dist_thresh: 4.0 # min distance between keypoints 

PLOTS:
  show: True
  save: False
  save_path: 'Code/plots/'

