DATA:
  rootdir: '/Datasets/'
  datasets: ['parking','kitti','malaga']
  curr_dataset: 'parking'
  init_img_1: '/images/img_00000.png'
  init_img_2: '/images/img_00005.png'

FEATURES:
  detectors: ['shi_tomasi', 'harris', 'sift']
  curr_detector: 0

HARRIS:
  kappa: 0.08
  corner_patch_size: 9
  num_keypoints: 200
  nonmaximum_supression_radius: 8
  descriptor_radius: 9
  match_lambda: 4

SHI_TOMASI:
  num_keypoints: 200
  corner_patch_size: 9
  nonmaximum_supression_radius: 8
  descriptor_radius: 9
  match_lambda: 4

SIFT:
  nfeatures: 200 # Not super sure about this yet
  #rotation_invariant: True
  contrast_threshold: 0.04 
  sigma: 1.0 # 1 or 1.6?
  #rescale_factor: 0.3
  n_otave_layers: 3
  #num_octaves: 5 #unused currently
  match_lambda: 4


